### ISSUE TITLE
Plugin throws error on damage

### ISSUE THREAD

**Issue by AzureMarble** [agblacky/timeout#1]
Error Log:

[21:14:44] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to Timeout v0.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1114) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:977) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:926) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2080) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1029) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1398) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:936) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:978) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1273) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:1923) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2493) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(SourceFile:166) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2418) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "future" because "fightTimer" is null
        at me.agblacky.timeout.DamageListener.onPlayerDamage(DamageListener.java:20) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

**Comment by agblacky** [comment]
Error should only occur, when the timer has run out and the player is still on the server, hence "fightTimer" is null

**Comment by AzureMarble** [comment]
Error should only occur, when the timer has run out and the player is still on the server, hence "fightTimer" is null
